Product List UI Finished
huydg11/ecommerce-app pull request #1
Opened 2024-10-14 10:11 UTC by huydg11

2024-10-14 10:18 UTC, mynv03 commented
add thêm phần này vào description này 
PR Description Template:
### Link Ticket:

### 1. Evidence (GIFs / Images)
Images or GIFs demonstrating the feature in action or the bug before and after the fix.
### 2. Ticket Requirement (Summary)
*Short Requirement*: Provide a brief summary of the requirements from the ticket.
### 3. Developer Summary
*Implemented Changes*: Provide a concise summary of what changes have been made in the codebase. Highlight any significant alterations or decisions taken during development.
### 4. Solution Description
*Developer Notes*: Solution checklist from the *Development* ticket.
| Task | Description | Done |
|------|-------------|------|
| Task 1 | Detailed description of Task 1 | :white_check_mark:  |
| Task 2 | Detailed description of Task 2 | :white_check_mark:  |
| Task 3 | Detailed description of Task 3 | :white_check_mark: |
| Task 4 | Detailed description of Task 4 | :white_check_mark:  |
| Task 5 | Detailed description of Task 5 | :white_check_mark: |

2024-10-14 17:33 UTC, MinhHoang141 requested changes
- Fix all comment
- Check if any other places have same errors.

2024-10-14 17:33 UTC, MinhHoang141 commented on src/@components/home.tsx
>      </div>
div is not needed.

2024-10-14 17:33 UTC, MinhHoang141 commented on src/@components/showProduct.tsx
> +    <div className="row row-cols-1 row-cols-md-2 g-4" style={{ justifyContent: 'space-around' }}>
If can, change to using tailwind for style instead of inline style

2024-10-14 17:33 UTC, MinhHoang141 commented on src/@components/showProduct.tsx
> +
What if the product is not available? Should we still display Loading... ?

2024-10-14 17:33 UTC, MinhHoang141 commented on src/@components/showProduct.tsx
> +                <div className="col" key={product.id} style={{ maxWidth: '300px' }}>
change to tailwind css

2024-10-14 17:33 UTC, MinhHoang141 commented on src/@components/showProduct.tsx
> +                            style={{ objectFit: 'contain', height: '200px' }}
already have className, no need for inline style

2024-10-14 17:33 UTC, MinhHoang141 commented on src/@components/showProduct.tsx
>  }, [ItemNumber]);
variables always camelCase

2024-10-14 17:33 UTC, MinhHoang141 commented on src/@components/showallProduct.tsx
> +        <div className="row row-cols-1 row-cols-md-2 g-4" style={{ justifyContent: 'space-around' }}>
tailwind css

2024-10-14 17:33 UTC, MinhHoang141 commented on src/@components/showallProduct.tsx
> +                        </div>
check review in the last file

2024-10-16 17:58 UTC, mynv03 commented
@huydg11 build fails, pls check
![image](https://github.com/user-attachments/assets/6a297f9b-cd81-483c-88d8-7bddbf866785)

2024-10-16 18:11 UTC, mynv03 requested changes

2024-10-16 18:11 UTC, mynv03 commented on src/@components/showProduct.tsx
- Đặt lại tên file cho phù hợp
- Chia lại cấu trúc file theo hướng dẫn ở đây https://www.tiepphan.com/practical-react-project-structure-2024/

2024-10-16 18:11 UTC, mynv03 commented on src/@components/showallProduct.tsx
- Đặt lại tên file cho phù hợp

2024-10-16 18:11 UTC, mynv03 commented on src/@components/SearchProduct.tsx
The name should be ProductItem

2024-10-16 18:11 UTC, mynv03 commented on src/@components/ListAllProduct.tsx
The name should be ProductList

2024-10-16 18:11 UTC, mynv03 commented on src/@components/SearchProduct.tsx
> +const ProductResult = () => {
I think variable name should be ProductItem

2024-10-16 18:11 UTC, mynv03 commented on src/@components/home.tsx
the name should be Home.ts

2024-10-16 18:11 UTC, mynv03 commented on src/@components/home.tsx
>  import React, { useState } from 'react';
delete redundant lib

2024-10-16 18:11 UTC, mynv03 commented on src/@components/home.tsx
>  import { useNavigate } from 'react-router-dom';
redundant lib

2024-10-16 18:11 UTC, mynv03 commented on src/@components/SearchProduct.tsx
> +import React, { useEffect, useState } from 'react';
redundant lib

2024-10-16 18:11 UTC, mynv03 commented on src/App.tsx
>  import './App.css';
redundant lib

2024-10-16 18:11 UTC, mynv03 commented on src/App.tsx
> +import Home from './@components/Home';
check fails URL

2024-10-16 18:11 UTC, mynv03 commented on src/@components/ListAllProduct.tsx
> +                                <p className="card-text">{product.description}</p>
the description should not be show all. I think you can limit it like the example. Search keyword "limit text line"
![image](https://github.com/user-attachments/assets/a34c9d0f-c807-4af5-9a8e-3e5406904ddd)

2024-10-22 03:45 UTC, MinhHoang141 requested changes
- Fix 1 comment
- Add lint library for React TSX

2024-10-22 03:45 UTC, MinhHoang141 commented on src/App.tsx
> +    { path: '/products/:productid', element: <ProductResult /> },
productId is correct. Don't change it to lowercase

2024-10-24 02:12 UTC, mynv03 approved these changes
done

2024-10-28 03:24 UTC, MinhHoang141 approved these changes

2024-10-28 03:59 UTC, merged